# fly.toml app configuration file generated for test-dind on 2023-08-22T16:12:28+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "test-dind"
primary_region = "lhr"

[build]
  dockerfile = "Dockerfile"
  ignorefile = ".dockerignore"

[[services]]
  protocol = "tcp"
  internal_port = 3000
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 1

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
